from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')
inc = [cwd, os.path.join(cwd, '../../app_utils')]

group = DefineGroup('App_bike_computer', src, depend=['BIKE_COMPUTER'], CPPPATH=inc)

Return('group')
