from building import *
import os

cwd = GetCurrentDir()
src = []
if not GetDepend('BSP_USING_PC_SIMULATOR'):
    src = Glob('*.c')
inc = [cwd, os.path.join(cwd, '../../app_utils')]

group = DefineGroup('App_file_manager', src, depend = [''], CPPPATH = inc)

Return('group')
