#ifndef AGENT_PET_IMAGE_TRANSFER_H
#define AGENT_PET_IMAGE_TRANSFER_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define AGENTPET_IMAGE_CONTROL_FRAME_SIZE (20U)
#define AGENTPET_IMAGE_DIGEST_FRAME_SIZE  (32U)
#define AGENTPET_IMAGE_MD5_SIZE           (16U)
#define AGENTPET_IMAGE_MAX_PACKET_SIZE    (244U)
#define AGENTPET_IMAGE_MAX_FILE_SIZE      (512U * 1024U)
#define AGENTPET_IMAGE_PATH               "/pet.img"
#define AGENTPET_IMAGE_LEGACY_PATH        "/pet.jpg"
#define AGENTPET_IMAGE_LVGL_PATH          "/:/pet.img"
#define AGENTPET_IMAGE_FORMAT_NONE        (0U)
#define AGENTPET_IMAGE_FORMAT_JPEG        (1U)
#define AGENTPET_IMAGE_FORMAT_GIF         (2U)

typedef enum _AGENTPET_IMAGE_STATE
{
    AGENTPET_IMAGE_IDLE = 0,
    AGENTPET_IMAGE_RECEIVING,
    AGENTPET_IMAGE_READY,
    AGENTPET_IMAGE_ERROR
} AGENTPET_IMAGE_STATE;

typedef enum _AGENTPET_IMAGE_RESULT
{
    AGENTPET_IMAGE_RESULT_ACCEPTED = 0,
    AGENTPET_IMAGE_RESULT_COMMITTED = 1,
    AGENTPET_IMAGE_RESULT_RESET = 2,
    AGENTPET_IMAGE_ERROR_INVALID_PARAMETER = 100,
    AGENTPET_IMAGE_ERROR_FRAME = 101,
    AGENTPET_IMAGE_ERROR_CRC = 102,
    AGENTPET_IMAGE_ERROR_STATE = 103,
    AGENTPET_IMAGE_ERROR_SIZE = 104,
    AGENTPET_IMAGE_ERROR_OFFSET = 105,
    AGENTPET_IMAGE_ERROR_STORAGE = 106,
    AGENTPET_IMAGE_ERROR_FORMAT = 107
} AGENTPET_IMAGE_RESULT;

typedef struct _AGENTPET_IMAGE_STATUS
{
    AGENTPET_IMAGE_STATE eState;
    bool bImageAvailable;
    uint32_t ulReceived;
    uint32_t ulTotal;
    uint32_t ulGeneration;
    AGENTPET_IMAGE_RESULT eLastResult;
    uint8_t ucFormat;
} AGENTPET_IMAGE_STATUS;

void AGENTPETIMAGE_Init(void);
void AGENTPETIMAGE_ResetTransfer(void);
bool AGENTPETIMAGE_QueueFrame(const uint8_t *pFrame, size_t ulLength);
AGENTPET_IMAGE_RESULT AGENTPETIMAGE_ProcessFrame(
    const uint8_t *pFrame,
    size_t ulLength);
bool AGENTPETIMAGE_GetStatus(AGENTPET_IMAGE_STATUS *pStatus);
bool AGENTPETIMAGE_GetDigest(bool *pAvailable, uint8_t *pDigest);

#endif /* AGENT_PET_IMAGE_TRANSFER_H */
