#ifndef AUDIO_DIAGNOSTICS_H
#define AUDIO_DIAGNOSTICS_H

#include <stdint.h>

/* AUDIO_DIAGNOSTIC_PHASE: Persistent progress markers for short-effect playback.
 * Values are stored in the 16-bit module field of RTC backup register 9. The
 * 0xA1xx range is reserved by this application and remains readable after a
 * watchdog reset.
 */
typedef enum _AUDIO_DIAGNOSTIC_PHASE
{
    AUDIO_DIAG_PHASE_IDLE = 0xA100,
    AUDIO_DIAG_PHASE_EFFECT_QUEUED = 0xA101,
    AUDIO_DIAG_PHASE_EFFECT_START = 0xA102,
    AUDIO_DIAG_PHASE_FILE_OPENED = 0xA103,
    AUDIO_DIAG_PHASE_HEADER_VALID = 0xA104,
    AUDIO_DIAG_PHASE_AUDIO_OPEN_BEGIN = 0xA105,
    AUDIO_DIAG_PHASE_AUDIO_OPEN_DONE = 0xA106,
    AUDIO_DIAG_PHASE_WRITE_PROGRESS = 0xA107,
    AUDIO_DIAG_PHASE_DRAIN_BEGIN = 0xA108,
    AUDIO_DIAG_PHASE_AUDIO_CLOSE_BEGIN = 0xA109,
    AUDIO_DIAG_PHASE_EFFECT_DONE = 0xA10A,
    AUDIO_DIAG_PHASE_EFFECT_ERROR = 0xA10F,
    AUDIO_DIAG_PHASE_SPEAKER_OPEN_BEGIN = 0xA110,
    AUDIO_DIAG_PHASE_AUDPRC_START_BEGIN = 0xA111,
    AUDIO_DIAG_PHASE_AUDPRC_START_DONE = 0xA112,
    AUDIO_DIAG_PHASE_CODEC_START_BEGIN = 0xA113,
    AUDIO_DIAG_PHASE_CODEC_START_DONE = 0xA114,
    AUDIO_DIAG_PHASE_PA_START_BEGIN = 0xA115,
    AUDIO_DIAG_PHASE_PA_GPIO_DONE = 0xA116,
    AUDIO_DIAG_PHASE_PA_WAIT_BEGIN = 0xA117,
    AUDIO_DIAG_PHASE_PA_WAIT_DONE = 0xA118,
    AUDIO_DIAG_PHASE_DAC_UNMUTE_BEGIN = 0xA119,
    AUDIO_DIAG_PHASE_SPEAKER_OPEN_DONE = 0xA11A,
    AUDIO_DIAG_PHASE_TX_IRQ_ENTER = 0xA11B,
    AUDIO_DIAG_PHASE_TX_BUFFER_BEGIN = 0xA11C,
    AUDIO_DIAG_PHASE_TX_BUFFER_DONE = 0xA11D,
    AUDIO_DIAG_PHASE_TX_IRQ_EXIT = 0xA11E,
} AUDIO_DIAGNOSTIC_PHASE;

void AUDIODIAG_SetPhase(AUDIO_DIAGNOSTIC_PHASE ePhase);
void AUDIODIAG_ServerStageHook(uint16_t usPhase);

#endif /* AUDIO_DIAGNOSTICS_H */
