Import('RTT_ROOT')
Import('rtconfig')
from building import *
import os

cwd = GetCurrentDir()
src = ['main.c']

if GetDepend('BSP_BLE_SIBLES') and os.path.exists(os.path.join(cwd, 'ble_app.c')):
    src+=['ble_app.c']

if GetDepend('BSP_BT_APP') and os.path.exists(os.path.join(cwd, 'bt_app.c')):
    src+=['bt_app.c']

if GetDepend('BSP_SHARE_PREFS'):
    src+=['watch_settings.c']

if GetDepend('CFG_AV_SNK'):
    src+=['bt_audio_sink.c']

if GetDepend('AUDIO_LOCAL_MUSIC'):
    src+=['local_music_player.c']

if GetDepend('BSP_BLE_SIBLES'):
    src+=['ble_watch_link.c']

if GetDepend('BSP_BLE_WATCH_FACE'):
    src+=['badge_transfer.c']

if GetDepend('BSP_USING_DATA_SVC'):
    src+=['ble_ios_services.c']


CPPPATH = [cwd]

group = DefineGroup('App_utils', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
