from building import *
import os

cwd = GetCurrentDir()
src = []
if GetDepend('AGENT_PET_USING_TF_CARD') and not GetDepend('BSP_USING_PC_SIMULATOR'):
    src = Glob('*.c')
inc = [cwd, os.path.join(cwd, '../../app_utils')]

group = DefineGroup('App_recorder', src, depend = [''], CPPPATH = inc)

Return('group')
