# PC simulator adapter sources plus the hardware pet UI sources.
# The simulator compiles the firmware UI directory directly. There is no copied
# UI tree to drift, and new .c files added to the pet app are picked up
# automatically on the next build.
from building import *
import os

cwd = GetCurrentDir()
pet_src = os.path.normpath(os.path.join(cwd, '../src/gui_apps/pet'))
app_utils = os.path.normpath(os.path.join(cwd, '../src/app_utils'))

src = Glob('*.c')
src += Glob(os.path.join(pet_src, '*.c'))

inc = [cwd, pet_src, app_utils]

group = DefineGroup('pet_sim', src, depend = ['PKG_USING_LITTLEVGL2RTT'], CPPPATH = inc)
Return('group')
