# Image resources for the pet simulator.
# Convert the same mascot PNG used by the hardware resource tree.
from building import *
import os
import rtconfig

cwd = GetCurrentDir()
shared_mascot = os.path.normpath(os.path.join(
    cwd,
    '../../../src/resource/images/common/ezip/agent_pet_mascot.png'))
img_flags = '-rgb565 -section ROM3_IMG '

objs = Env.ImgResource([shared_mascot], img_flags + '-cfile 1 -simu')

if GetOption('no_cc'):
    objs = []

objs = DefineGroup('pet_resource', objs, depend = ['PKG_USING_LITTLEVGL2RTT'])

Return('objs')
