from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')
app_utils = os.path.join(cwd, '..', '..', 'app_utils')
local_ccflags = ''

if not GetDepend('AGENT_PET_MOMO_PLAY_BALL'):
    src = [node for node in src
           if os.path.basename(str(node)) != 'momo_play_ball.c']

if not GetDepend('BSP_USING_PC_SIMULATOR'):
    local_ccflags = ' -Wall -Wextra -Wno-cast-function-type -Werror'

group = DefineGroup(
    'App_pet_motion',
    src,
    depend = [''],
    CPPPATH = [cwd, app_utils],
    LOCAL_CCFLAGS = local_ccflags)

Return('group')
