from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')
if not GetDepend('MOMO_AGENT_SQUAD'):
    src = [source for source in src if not str(source).endswith('momo_agent_squad.c')]
app_utils = os.path.join(cwd, '..', '..', 'app_utils')
local_ccflags = ''

if not GetDepend('BSP_USING_PC_SIMULATOR'):
    local_ccflags = ' -Wall -Wextra -Wno-cast-function-type -Werror'

group = DefineGroup(
    'App_pet_motion',
    src,
    depend = [''],
    CPPPATH = [cwd, app_utils],
    LOCAL_CCFLAGS = local_ccflags)

Return('group')
