CONFIG_LCD_WINDOWS=y
CONFIG_RT_USING_POSIX=n
CONFIG_RT_USING_USER_MAIN=n
CONFIG_RT_USING_HWMAILBOX=n
CONFIG_USING_BUTTON_LIB=n
CONFIG_USING_CPU_USAGE_PROFILER=n
CONFIG_RT_USING_PM=n
CONFIG_RT_USING_RTC=n
CONFIG_RT_USING_ALARM=n
CONFIG_BSP_USING_ONCHIP_RTC=n
CONFIG_RT_USING_BLUETOOTH=n
CONFIG_BLUETOOTH=n
CONFIG_BT_PROFILE_CUSTOMIZE=n
CONFIG_CFG_AV=n
CONFIG_CFG_AV_SNK=n
CONFIG_CFG_AVRCP=n
CONFIG_BSP_USING_DATA_SVC=n
CONFIG_BSP_BLE_SERIAL_TRANSMISSION=n
CONFIG_BSP_BLE_WATCH_FACE=n
CONFIG_AUDIO=n
CONFIG_AUDIO_LOCAL_MUSIC=n
CONFIG_PKG_USING_WEBRTC=n
CONFIG_WEBRTC_ANS_FIX=n
CONFIG_WEBRTC_AGC_FIX=n
CONFIG_WEBRTC_AECM=n
CONFIG_FFT_USING_WEBRTC=n
CONFIG_PKG_USING_CMBACKTRACE=n
CONFIG_BSP_USING_WDT=n
